=== nets4geeks/SPCatalogMaker/catalogs/acctp/catalog/cd.schema.json
{
  "$schema" : "http://json-schema.org/draft-04/schema#",
  "title" : "JSON schema",
  "properties" : {
    "id" : {
      "title" : "ID",
      "description" : "Pattern's ID (compatible with OWL)",
      "type" : "string"
    },
    "metadata" : {
      "title" : "Metadata section",
      "type" : "object",
      "properties" : {
        "ns:textReference" : {
          "type" : "string",
          "title" : "Reference",
          "description" : "A bibliographic description"
        },
        "ns:textReviewProblem" : {
          "type" : "string",
          "title" : "Problem (review)",
          "description" : "Pattern’s problem (review)"
        },
        "ns:textReviewSolution" : {
          "type" : "string",
          "title" : "Solution (review)",
          "description" : "Pattern’s solution (review)"
        },
        "ns:textName" : {
          "type" : "string",
          "title" : "Name",
          "description" : "Pattern’s primary name"
        },
        "ns:textReviewContext" : {
          "type" : "string",
          "title" : "Context (review)",
          "description" : "Pattern’s context (review)"
        },
        "ns:textURL" : {
          "type" : "string",
          "title" : "URL",
          "description" : "URL(s) of pattern's webpage"
        }
      }
    },
    "organization" : {
      "title" : "Organization and scope section",
      "type" : "object",
      "properties" : {
        "ns:relatesTo" : {
          "title" : "Related Pattern",
          "description" : "Enumerates patterns that are related to this one.",
          "type" : "array",
          "uniqueItems" : true,
          "items" : {
            "type" : "string"
          }
        },
        "ns:hasGroup" : {
          "title" : "Group",
          "description" : "Pattern's group",
          "type" : "array",
          "uniqueItems" : true,
          "items" : {
            "type" : "string"
          }
        },
        "ns:usesPattern" : {
          "title" : "Used pattern",
          "description" : "Enumerates patterns that are used by this one.",
          "type" : "array",
          "uniqueItems" : true,
          "items" : {
            "type" : "string"
          }
        },
        "ns:hasType" : {
          "title" : "Type",
          "description" : "Type of a pattern",
          "type" : "array",
          "uniqueItems" : true,
          "items" : {
            "type" : "string",
            "enum" : [ "ns:type_SecurityPattern", "ns:type_ThreatPattern", "ns:type_MisusePattern" ]
          }
        },
        "ns:isChildOf" : {
          "title" : "Parent pattern",
          "description" : "For a concrete pattern shows from which abstract pattern it has been made.",
          "type" : "array",
          "uniqueItems" : true,
          "items" : {
            "type" : "string"
          }
        },
        "ns:hasTemplate" : {
          "title" : "Template",
          "description" : "Template, used to describe a pattern.",
          "type" : "array",
          "uniqueItems" : true,
          "items" : {
            "type" : "string",
            "enum" : [ "ns:template_POSA", "ns:template_GOF" ]
          }
        }
      }
    },
    "common" : {
      "title" : "Common section",
      "type" : "object",
      "properties" : {
        "ns:hasArchitecturalLayer" : {
          "title" : "Architectural layer",
          "type" : "array",
          "uniqueItems" : true,
          "items" : {
            "type" : "string",
            "enum" : [ "ns:al_DistributionLayer", "ns:al_ClientLayer", "ns:al_NetworkLayer", "ns:al_TransportLayer", "ns:al_DataLayer", "ns:al_LogicLayer", "ns:al_PlatformAndOperatingSystem" ]
          }
        },
        "ns:hasResponseType" : {
          "title" : "Response type",
          "type" : "array",
          "uniqueItems" : true,
          "items" : {
            "type" : "string",
            "enum" : [ "ns:rt_Prevention", "ns:rt_Forensics", "ns:rt_Recovery", "ns:rt_Mitigation", "ns:rt_Deterrence", "ns:rt_Avoidance", "ns:rt_Detection" ]
          }
        },
        "ns:hasDomain" : {
          "title" : "Domain",
          "description" : "Tells to which domain(s) a pattern belongs to.",
          "type" : "array",
          "uniqueItems" : true,
          "items" : {
            "type" : "string",
            "enum" : [ "ns:domain_SCADA", "ns:domain_PaaS", "ns:domain_Military", "ns:domain_FogComputing", "ns:domain_CloudComputing", "ns:domain_InternetOfThings", "ns:domain_GridComputing", "ns:domain_IaaS", "ns:domain_NFV", "ns:domain_EdgeComputing", "ns:domain_SaaS", "ns:domain_ECommerce" ]
          }
        },
        "ns:hasLifecycleStage" : {
          "title" : "Lifecycle stage",
          "type" : "array",
          "uniqueItems" : true,
          "items" : {
            "type" : "string",
            "enum" : [ "ns:lc_ArchitectureAndDesign", "ns:lc_Deployment", "ns:lc_Operations", "ns:lc_Requirements", "ns:lc_Implementation", "ns:lc_BuildAndCompilation", "ns:lc_SystemConfiguration", "ns:lc_Installation" ]
          }
        },
        "ns:hasSecurityLevel" : {
          "title" : "Security level",
          "type" : "array",
          "uniqueItems" : true,
          "items" : {
            "type" : "string",
            "enum" : [ "ns:sl_PhysicalSecurity", "ns:sl_PersonnelSecurity", "ns:sl_CommunicationAndDataSecurity", "ns:sl_OperationalSecurity" ]
          }
        },
        "ns:hasConstraintLevel" : {
          "title" : "Constraint level",
          "type" : "array",
          "uniqueItems" : true,
          "items" : {
            "type" : "string",
            "enum" : [ "ns:cl_OrganizationalLevel", "ns:cl_HumanLevel", "ns:cl_MechanismLevel", "ns:cl_RegulatoryLevel" ]
          }
        }
      }
    },
    "context" : {
      "title" : "Context section",
      "type" : "object",
      "properties" : {
        "ns:hasAffectedComponent" : {
          "title" : "Affected component",
          "description" : "Tells which common component(s) a pattern affects.",
          "type" : "array",
          "uniqueItems" : true,
          "items" : {
            "type" : "string",
            "enum" : [ "su:comp_RemoteUser", "su:comp_CloudInfrastructure", "ns:component_Hardware", "su:comp_SaaSApplication", "su:comp_ExternalService", "ns:component_Actor", "ns:component_Software", "su:comp_PaaSApplication", "su:comp_ComplianceManager", "su:comp_CloudApplication", "su:comp_PriivacyManager" ]
          }
        },
        "ns:hasAffectedFunction" : {
          "title" : "Affected function",
          "description" : "Tells which system function(s) a pattern affects.",
          "type" : "array",
          "uniqueItems" : true,
          "items" : {
            "type" : "string",
            "enum" : [ "ns:function_Software", "ns:function_Actor", "ns:function_Hardware" ]
          }
        }
      }
    },
    "security" : {
      "title" : "Security section",
      "type" : "object",
      "properties" : {
        "ns:hasAggressor" : {
          "title" : "Aggressor",
          "description" : "Possible aggressor",
          "type" : "array",
          "uniqueItems" : true,
          "items" : {
            "type" : "string",
            "enum" : [ "su:comp_RemoteUser", "su:comp_CloudInfrastructure", "ns:component_Hardware", "su:comp_SaaSApplication", "su:comp_ExternalService", "ns:component_Actor", "ns:component_Software", "su:comp_PaaSApplication", "su:comp_ComplianceManager", "su:comp_CloudApplication", "su:comp_PriivacyManager" ]
          }
        },
        "ns:hasSTRIDE" : {
          "title" : "STRIDE",
          "description" : "Related STRIDE item(s)",
          "type" : "array",
          "uniqueItems" : true,
          "items" : {
            "type" : "string",
            "enum" : [ "ns:STRIDE_Repudiation", "ns:STRIDE_Tampering", "ns:STRIDE_Information_Disclosure", "ns:STRIDE_Elevation_of_Privilege", "ns:STRIDE_Spoofing", "ns:STRIDE_Denial_of_Service" ]
          }
        },
        "ns:hasAggressorRole" : {
          "type" : "array",
          "uniqueItems" : true,
          "items" : {
            "type" : "string",
            "enum" : [ "ns:role_Server", "ns:role_Client" ]
          }
        },
        "ns:hasWeakness" : {
          "title" : "Weakness (CWE-based)",
          "description" : "Possible related weknesses (CWE-based)",
          "type" : "array",
          "uniqueItems" : true,
          "items" : {
            "type" : "string"
          }
        },
        "ns:hasSecurityConcern" : {
          "title" : "Security concern",
          "description" : "Tells which security concern(s) a pattern touches.",
          "type" : "array",
          "uniqueItems" : true,
          "items" : {
            "type" : "string",
            "enum" : [ "ns:concern_RiskAssessment", "ns:concern_Maintenance", "ns:concern_AssessmentAuthorizationAndMonitoring", "ns:concern_MediaProtection", "ns:concern_SystemAndServicesAcquisition", "ns:concern_IdentificationAndAuthentication", "ns:concern_IncidentResponse", "ns:concern_AuditAndAccountability", "ns:concern_ConfigurationManagement", "ns:concern_SystemAndInformationIntegrity", "ns:concern_AwarenessAndTraining", "ns:concern_SystemAndCommunicationsProtection", "ns:concern_ContingencyPlanning", "ns:concern_Planning", "ns:concern_ProgramManagement", "ns:concern_AccessControl", "ns:concern_PhysicalAndEnvironmentalProtection", "ns:concern_PersonnelSecurity" ]
          }
        },
        "ns:hasThreat" : {
          "title" : "Threat (CAPEC-based)",
          "description" : "Tells what threats (CAPEC attack patterns) a pattern describes with connection to component(s) and function(s",
          "type" : "array",
          "uniqueItems" : true,
          "items" : {
            "type" : "string",
            "enum" : [ "ns:threat_Flooding", "ns:threat_InformationGathering", "ns:threat_AuthenticationBypass", "ns:threat_EnvironmentManipulation", "ns:threat_PriviledgeEscalation", "ns:threat_InputDataManipulation", "ns:threat_ProtocolAnalysis", "ns:threat_SharedDataManipulation", "ns:threat_ManInTheMiddle", "ns:threat_Footprinting", "ns:threat_Malware", "ns:threat_Excavation", "ns:threat_IdentitySpoofing", "ns:threat_ContentSpoofing", "ns:threat_SessionManipulation", "ns:threat_BufferManipulation", "ns:threat_CodeInjection", "ns:threat_Interception", "ns:threat_ManipulationAPI", "ns:threat_ExcessiveAllocation" ]
          }
        }
      }
    }
  }
}

=== nets4geeks/SPCatalogMaker/catalogs/acctp/catalog/threatBA09_SecurityIssuesOfSLA.json
{
  "id": "threatBA09_SecurityIssuesOfSLA",
  "metadata": {
    "ns:textReviewContext": "Compliance manager works with cloud application",
    "ns:textName": "BA09 Security Issues Of SLA",
    "ns:textReviewSolution": "",
    "ns:textURL": "",
    "ns:textReviewProblem": "Incorrect or unclear information security section of SLA",
    "ns:textReference": "OI-4: Issues emerging because of poor SLA specification [SECCRIT]; V.31: Lack of completeness and transparency in terms of use [ENISA]; V.23: SLA clauses with conflicting promises to different stakeholders [ENISA]; V.24: SLA clauses containing excessive business risk [ENISA]"
  },
  "organization": {
    "ns:usesPattern": [],
    "ns:hasGroup": [],
    "ns:hasType": ["ns:type_ThreatPattern"],
    "ns:hasTemplate": [],
    "ns:relatesTo": [],
    "ns:isChildOf": []
  },
  "common": {
    "ns:hasArchitecturalLayer": [],
    "ns:hasResponseType": [],
    "ns:hasDomain": [],
    "ns:hasSecurityLevel": [],
    "ns:hasLifecycleStage": [],
    "ns:hasConstraintLevel": []
  },
  "context": {
    "ns:hasAffectedFunction": [],
    "ns:hasAffectedComponent": ["su:comp_CloudApplication"]
  },
  "security": {
    "ns:hasThreat": [],
    "ns:hasAggressor": ["su:comp_ComplianceManager"],
    "ns:hasAggressorRole": ["ns:role_Client"],
    "ns:hasWeakness": [],
    "ns:hasSTRIDE": [],
    "ns:hasSecurityConcern": []
  }
}

=== nets4geeks/SPCatalogMaker/catalogs/acctp/catalog/threatAD06_BackupOfCloudApplicationStolen.json
{
  "id": "threatAD06_BackupOfCloudApplicationStolen",
  "metadata": {
    "ns:textReviewContext": "Someone interacts with a cloud application",
    "ns:textName": "AD06 Backup Of Cloud Application Stolen",
    "ns:textReviewSolution": "",
    "ns:textURL": "",
    "ns:textReviewProblem": "Disclosure of cloud application backup",
    "ns:textReference": "R.32: BACKUPS LOST, STOLEN [ENISA]"
  },
  "organization": {
    "ns:usesPattern": [],
    "ns:hasGroup": [],
    "ns:hasType": ["ns:type_ThreatPattern"],
    "ns:hasTemplate": [],
    "ns:relatesTo": [],
    "ns:isChildOf": []
  },
  "common": {
    "ns:hasArchitecturalLayer": [],
    "ns:hasResponseType": [],
    "ns:hasDomain": [],
    "ns:hasSecurityLevel": [],
    "ns:hasLifecycleStage": [],
    "ns:hasConstraintLevel": []
  },
  "context": {
    "ns:hasAffectedFunction": [],
    "ns:hasAffectedComponent": ["su:comp_CloudApplication"]
  },
  "security": {
    "ns:hasThreat": [],
    "ns:hasAggressor": ["su:comp_CloudApplication", "su:comp_ExternalService", "su:comp_RemoteUser"],
    "ns:hasAggressorRole": ["ns:role_Client"],
    "ns:hasWeakness": [],
    "ns:hasSTRIDE": ["ns:STRIDE_Information_Disclosure"],
    "ns:hasSecurityConcern": []
  }
}

=== nets4geeks/SPCatalogMaker/catalogs/acctp/catalog/threatAB01_FailureOfCloudApplication.json
{
  "id": "threatAB01_FailureOfCloudApplication",
  "metadata": {
    "ns:textReviewContext": "Someone interacts with a cloud application",
    "ns:textName": "AB01 Failure Of Cloud Application",
    "ns:textReviewSolution": "Ensure fault tolerance of the remote service; Apply a standby remote service; Replace the remote service by a local one;",
    "ns:textURL": "",
    "ns:textReviewProblem": "Unexpected failure of the cloud application"
  },
  "organization": {
    "ns:usesPattern": [],
    "ns:hasGroup": [],
    "ns:hasType": ["ns:type_ThreatPattern"],
    "ns:hasTemplate": [],
    "ns:relatesTo": [],
    "ns:isChildOf": []
  },
  "common": {
    "ns:hasArchitecturalLayer": [],
    "ns:hasResponseType": [],
    "ns:hasDomain": [],
    "ns:hasSecurityLevel": [],
    "ns:hasLifecycleStage": [],
    "ns:hasConstraintLevel": []
  },
  "context": {
    "ns:hasAffectedFunction": [],
    "ns:hasAffectedComponent": ["su:comp_CloudApplication", "su:comp_RemoteUser", "su:comp_ExternalService" ]
  },
  "security": {
    "ns:hasThreat": [],
    "ns:hasAggressor": ["su:comp_CloudApplication"],
    "ns:hasAggressorRole": ["ns:role_Server"],
    "ns:hasWeakness": [],
    "ns:hasSTRIDE": ["ns:STRIDE_Denial_of_Service"],
    "ns:hasSecurityConcern": []
  }
}

=== nets4geeks/SPCatalogMaker/catalogs/acctp/catalog/threatAB02_ConnectionLostToCloudApplication.json
{
  "id": "threatAB02_ConnectionLostToCloudApplication",
  "metadata": {
    "ns:textReviewContext": "Someone interacts with a cloud application",
    "ns:textName": "AB02 Connection Lost To Cloud Application",
    "ns:textReviewSolution": "Ensure fault tolerance of the network connection; Apply clustrer-like configuration and load balancing of the cloud application; Apply Multi Availability Zone Deployment; Apply Content Distribution Networks (CDN)",
    "ns:textURL": "",
    "ns:textReviewProblem": "Connection lost to the cloud application",
    "ns:textReference": "BNA-3: Loss of wide-area network connectivity... [SECCRIT]"
  },
  "organization": {
    "ns:usesPattern": [],
    "ns:hasGroup": [],
    "ns:hasType": ["ns:type_ThreatPattern"],
    "ns:hasTemplate": [],
    "ns:relatesTo": [],
    "ns:isChildOf": []
  },
  "common": {
    "ns:hasArchitecturalLayer": [],
    "ns:hasResponseType": [],
    "ns:hasDomain": [],
    "ns:hasSecurityLevel": [],
    "ns:hasLifecycleStage": [],
    "ns:hasConstraintLevel": []
  },
  "context": {
    "ns:hasAffectedFunction": [],
    "ns:hasAffectedComponent": ["su:comp_CloudApplication", "su:comp_RemoteUser", "su:comp_ExternalService" ]
  },
  "security": {
    "ns:hasThreat": [],
    "ns:hasAggressor": ["su:comp_CloudApplication"],
    "ns:hasAggressorRole": ["ns:role_Server"],
    "ns:hasWeakness": [],
    "ns:hasSTRIDE": ["ns:STRIDE_Denial_of_Service"],
    "ns:hasSecurityConcern": []
  }
}

=== nets4geeks/SPCatalogMaker/catalogs/acctp/catalog/threatBA12_ConfiscationOfComputerHardware.json
{
  "id": "threatBA12_ConfiscationOfComputerHardware",
  "metadata": {
    "ns:textReviewContext": "Compliance manager works with cloud application",
    "ns:textName": "BA12 Confiscation Of Computer Hardware",
    "ns:textReviewSolution": "",
    "ns:textURL": "",
    "ns:textReviewProblem": "Confiscation of computer hardware of cloud provider as a result of subpoena by law-enforcement agencies",
    "ns:textReference": "R.21: Subpoena and  Eâ€“Discovery [ENISA]"
  },
  "organization": {
    "ns:usesPattern": [],
    "ns:hasGroup": [],
    "ns:hasType": ["ns:type_ThreatPattern"],
    "ns:hasTemplate": [],
    "ns:relatesTo": [],
    "ns:isChildOf": []
  },
  "common": {
    "ns:hasArchitecturalLayer": [],
    "ns:hasResponseType": [],
    "ns:hasDomain": [],
    "ns:hasSecurityLevel": [],
    "ns:hasLifecycleStage": [],
    "ns:hasConstraintLevel": []
  },
  "context": {
    "ns:hasAffectedFunction": [],
    "ns:hasAffectedComponent": ["su:comp_CloudApplication"]
  },
  "security": {
    "ns:hasThreat": [],
    "ns:hasAggressor": ["su:comp_ComplianceManager"],
    "ns:hasAggressorRole": ["ns:role_Client"],
    "ns:hasWeakness": [],
    "ns:hasSTRIDE": ["ns:STRIDE_Information_Disclosure","ns:STRIDE_Denial_of_Service"],
    "ns:hasSecurityConcern": []
  }
}

=== nets4geeks/SPCatalogMaker/catalogs/acctp/catalog/threatBA11_SoftwareLicenseIssues.json
{
  "id": "threatBA11_SoftwareLicenseIssues",
  "metadata": {
    "ns:textReviewContext": "Compliance manager works with cloud application",
    "ns:textName": "BA11 Software License Issues",
    "ns:textReviewSolution": "",
    "ns:textURL": "",
    "ns:textReviewProblem": "Software license issues",
    "ns:textReference": "R.24: Licensing risks [ENISA]; TIS.064 [BDU]"
  },
  "organization": {
    "ns:usesPattern": [],
    "ns:hasGroup": [],
    "ns:hasType": ["ns:type_ThreatPattern"],
    "ns:hasTemplate": [],
    "ns:relatesTo": [],
    "ns:isChildOf": []
  },
  "common": {
    "ns:hasArchitecturalLayer": [],
    "ns:hasResponseType": [],
    "ns:hasDomain": [],
    "ns:hasSecurityLevel": [],
    "ns:hasLifecycleStage": [],
    "ns:hasConstraintLevel": []
  },
  "context": {
    "ns:hasAffectedFunction": [],
    "ns:hasAffectedComponent": ["su:comp_CloudApplication"]
  },
  "security": {
    "ns:hasThreat": [],
    "ns:hasAggressor": ["su:comp_ComplianceManager"],
    "ns:hasAggressorRole": ["ns:role_Client"],
    "ns:hasWeakness": [],
    "ns:hasSTRIDE": [],
    "ns:hasSecurityConcern": []
  }
}

=== nets4geeks/SPCatalogMaker/catalogs/acctp/catalog/threatBA04_HiddenDependenciesOfCloudInfrastructure.json
{
  "id": "threatBA04_HiddenDependenciesOfCloudInfrastructure",
  "metadata": {
    "ns:textReviewContext": "Compliance manager works with cloud application",
    "ns:textName": "BA04 Hidden Dependencies Of Cloud Infrastructure",
    "ns:textReviewSolution": "",
    "ns:textURL": "",
    "ns:textReviewProblem": "Hidden dependencies between components of cloud application and cloud infrastructure cause security issues of cloud application",
    "ns:textReference": "R.7: Supply chain failure [ENISA]"
  },
  "organization": {
    "ns:usesPattern": [],
    "ns:hasGroup": [],
    "ns:hasType": ["ns:type_ThreatPattern"],
    "ns:hasTemplate": [],
    "ns:relatesTo": [],
    "ns:isChildOf": []
  },
  "common": {
    "ns:hasArchitecturalLayer": [],
    "ns:hasResponseType": [],
    "ns:hasDomain": [],
    "ns:hasSecurityLevel": [],
    "ns:hasLifecycleStage": [],
    "ns:hasConstraintLevel": []
  },
  "context": {
    "ns:hasAffectedFunction": [],
    "ns:hasAffectedComponent": ["su:comp_CloudApplication"]
  },
  "security": {
    "ns:hasThreat": [],
    "ns:hasAggressor": ["su:comp_ComplianceManager"],
    "ns:hasAggressorRole": ["ns:role_Client"],
    "ns:hasWeakness": [],
    "ns:hasSTRIDE": ["ns:STRIDE_Denial_of_Service"],
    "ns:hasSecurityConcern": []
  }
}

=== nets4geeks/SPCatalogMaker/catalogs/acctp/catalog/threatAC01_MalwareFromCloudApplication.json
{
  "id": "threatAC01_MalwareFromCloudApplication",
  "metadata": {
    "ns:textReviewContext": "Remote user interacts with a cloud application",
    "ns:textName": "AC01 Malware From Cloud Application",
    "ns:textReviewSolution": "Apply antivirus software (Remote user); Apply malware scan (cloud application);",
    "ns:textURL": "",
    "ns:textReviewProblem": "Malicious content (malware) from the cloud application (affects remote user)"
  },
  "organization": {
    "ns:usesPattern": [],
    "ns:hasGroup": [],
    "ns:hasType": ["ns:type_ThreatPattern"],
    "ns:hasTemplate": [],
    "ns:relatesTo": [],
    "ns:isChildOf": []
  },
  "common": {
    "ns:hasArchitecturalLayer": [],
    "ns:hasResponseType": [],
    "ns:hasDomain": [],
    "ns:hasSecurityLevel": [],
    "ns:hasLifecycleStage": [],
    "ns:hasConstraintLevel": []
  },
  "context": {
    "ns:hasAffectedFunction": [],
    "ns:hasAffectedComponent": ["su:comp_RemoteUser"]
  },
  "security": {
    "ns:hasThreat": [],
    "ns:hasAggressor": ["su:comp_CloudApplication"],
    "ns:hasAggressorRole": ["ns:role_Server"],
    "ns:hasWeakness": [],
    "ns:hasSTRIDE": [],
    "ns:hasSecurityConcern": []
  }
}
