=== nets4geeks/SPCatalogMaker/catalogs/acctp/catalog/cd.schema.json
{
  "$schema" : "http://json-schema.org/draft-04/schema#",
  "title" : "JSON schema",
  "properties" : {
    "id" : {
      "title" : "ID",
      "description" : "Pattern's ID (compatible with OWL)",
      "type" : "string"
    },
    "metadata" : {
      "title" : "Metadata section",
      "type" : "object",
      "properties" : {
        "ns:textReference" : {
          "type" : "string",
          "title" : "Reference",
          "description" : "A bibliographic description"
        },
        "ns:textReviewProblem" : {
          "type" : "string",
          "title" : "Problem (review)",
          "description" : "Pattern’s problem (review)"
        },
        "ns:textReviewSolution" : {
          "type" : "string",
          "title" : "Solution (review)",
          "description" : "Pattern’s solution (review)"
        },
        "ns:textName" : {
          "type" : "string",
          "title" : "Name",
          "description" : "Pattern’s primary name"
        },
        "ns:textReviewContext" : {
          "type" : "string",
          "title" : "Context (review)",
          "description" : "Pattern’s context (review)"
        },
        "ns:textURL" : {
          "type" : "string",
          "title" : "URL",
          "description" : "URL(s) of pattern's webpage"
        }
      }
    },
    "organization" : {
      "title" : "Organization and scope section",
      "type" : "object",
      "properties" : {
        "ns:relatesTo" : {
          "title" : "Related Pattern",
          "description" : "Enumerates patterns that are related to this one.",
          "type" : "array",
          "uniqueItems" : true,
          "items" : {
            "type" : "string"
          }
        },
        "ns:hasGroup" : {
          "title" : "Group",
          "description" : "Pattern's group",
          "type" : "array",
          "uniqueItems" : true,
          "items" : {
            "type" : "string"
          }
        },
        "ns:usesPattern" : {
          "title" : "Used pattern",
          "description" : "Enumerates patterns that are used by this one.",
          "type" : "array",
          "uniqueItems" : true,
          "items" : {
            "type" : "string"
          }
        },
        "ns:hasType" : {
          "title" : "Type",
          "description" : "Type of a pattern",
          "type" : "array",
          "uniqueItems" : true,
          "items" : {
            "type" : "string",
            "enum" : [ "ns:type_SecurityPattern", "ns:type_ThreatPattern", "ns:type_MisusePattern" ]
          }
        },
        "ns:isChildOf" : {
          "title" : "Parent pattern",
          "description" : "For a concrete pattern shows from which abstract pattern it has been made.",
          "type" : "array",
          "uniqueItems" : true,
          "items" : {
            "type" : "string"
          }
        },
        "ns:hasTemplate" : {
          "title" : "Template",
          "description" : "Template, used to describe a pattern.",
          "type" : "array",
          "uniqueItems" : true,
          "items" : {
            "type" : "string",
            "enum" : [ "ns:template_POSA", "ns:template_GOF" ]
          }
        }
      }
    },
    "common" : {
      "title" : "Common section",
      "type" : "object",
      "properties" : {
        "ns:hasArchitecturalLayer" : {
          "title" : "Architectural layer",
          "type" : "array",
          "uniqueItems" : true,
          "items" : {
            "type" : "string",
            "enum" : [ "ns:al_DistributionLayer", "ns:al_ClientLayer", "ns:al_NetworkLayer", "ns:al_TransportLayer", "ns:al_DataLayer", "ns:al_LogicLayer", "ns:al_PlatformAndOperatingSystem" ]
          }
        },
        "ns:hasResponseType" : {
          "title" : "Response type",
          "type" : "array",
          "uniqueItems" : true,
          "items" : {
            "type" : "string",
            "enum" : [ "ns:rt_Prevention", "ns:rt_Forensics", "ns:rt_Recovery", "ns:rt_Mitigation", "ns:rt_Deterrence", "ns:rt_Avoidance", "ns:rt_Detection" ]
          }
        },
        "ns:hasDomain" : {
          "title" : "Domain",
          "description" : "Tells to which domain(s) a pattern belongs to.",
          "type" : "array",
          "uniqueItems" : true,
          "items" : {
            "type" : "string",
            "enum" : [ "ns:domain_SCADA", "ns:domain_PaaS", "ns:domain_Military", "ns:domain_FogComputing", "ns:domain_CloudComputing", "ns:domain_InternetOfThings", "ns:domain_GridComputing", "ns:domain_IaaS", "ns:domain_NFV", "ns:domain_EdgeComputing", "ns:domain_SaaS", "ns:domain_ECommerce" ]
          }
        },
        "ns:hasLifecycleStage" : {
          "title" : "Lifecycle stage",
          "type" : "array",
          "uniqueItems" : true,
          "items" : {
            "type" : "string",
            "enum" : [ "ns:lc_ArchitectureAndDesign", "ns:lc_Deployment", "ns:lc_Operations", "ns:lc_Requirements", "ns:lc_Implementation", "ns:lc_BuildAndCompilation", "ns:lc_SystemConfiguration", "ns:lc_Installation" ]
          }
        },
        "ns:hasSecurityLevel" : {
          "title" : "Security level",
          "type" : "array",
          "uniqueItems" : true,
          "items" : {
            "type" : "string",
            "enum" : [ "ns:sl_PhysicalSecurity", "ns:sl_PersonnelSecurity", "ns:sl_CommunicationAndDataSecurity", "ns:sl_OperationalSecurity" ]
          }
        },
        "ns:hasConstraintLevel" : {
          "title" : "Constraint level",
          "type" : "array",
          "uniqueItems" : true,
          "items" : {
            "type" : "string",
            "enum" : [ "ns:cl_OrganizationalLevel", "ns:cl_HumanLevel", "ns:cl_MechanismLevel", "ns:cl_RegulatoryLevel" ]
          }
        }
      }
    },
    "context" : {
      "title" : "Context section",
      "type" : "object",
      "properties" : {
        "ns:hasAffectedComponent" : {
          "title" : "Affected component",
          "description" : "Tells which common component(s) a pattern affects.",
          "type" : "array",
          "uniqueItems" : true,
          "items" : {
            "type" : "string",
            "enum" : [ "su:comp_RemoteUser", "su:comp_CloudInfrastructure", "ns:component_Hardware", "su:comp_SaaSApplication", "su:comp_ExternalService", "ns:component_Actor", "ns:component_Software", "su:comp_PaaSApplication", "su:comp_ComplianceManager", "su:comp_CloudApplication", "su:comp_PriivacyManager" ]
          }
        },
        "ns:hasAffectedFunction" : {
          "title" : "Affected function",
          "description" : "Tells which system function(s) a pattern affects.",
          "type" : "array",
          "uniqueItems" : true,
          "items" : {
            "type" : "string",
            "enum" : [ "ns:function_Software", "ns:function_Actor", "ns:function_Hardware" ]
          }
        }
      }
    },
    "security" : {
      "title" : "Security section",
      "type" : "object",
      "properties" : {
        "ns:hasAggressor" : {
          "title" : "Aggressor",
          "description" : "Possible aggressor",
          "type" : "array",
          "uniqueItems" : true,
          "items" : {
            "type" : "string",
            "enum" : [ "su:comp_RemoteUser", "su:comp_CloudInfrastructure", "ns:component_Hardware", "su:comp_SaaSApplication", "su:comp_ExternalService", "ns:component_Actor", "ns:component_Software", "su:comp_PaaSApplication", "su:comp_ComplianceManager", "su:comp_CloudApplication", "su:comp_PriivacyManager" ]
          }
        },
        "ns:hasSTRIDE" : {
          "title" : "STRIDE",
          "description" : "Related STRIDE item(s)",
          "type" : "array",
          "uniqueItems" : true,
          "items" : {
            "type" : "string",
            "enum" : [ "ns:STRIDE_Repudiation", "ns:STRIDE_Tampering", "ns:STRIDE_Information_Disclosure", "ns:STRIDE_Elevation_of_Privilege", "ns:STRIDE_Spoofing", "ns:STRIDE_Denial_of_Service" ]
          }
        },
        "ns:hasAggressorRole" : {
          "type" : "array",
          "uniqueItems" : true,
          "items" : {
            "type" : "string",
            "enum" : [ "ns:role_Server", "ns:role_Client" ]
          }
        },
        "ns:hasWeakness" : {
          "title" : "Weakness (CWE-based)",
          "description" : "Possible related weknesses (CWE-based)",
          "type" : "array",
          "uniqueItems" : true,
          "items" : {
            "type" : "string"
          }
        },
        "ns:hasSecurityConcern" : {
          "title" : "Security concern",
          "description" : "Tells which security concern(s) a pattern touches.",
          "type" : "array",
          "uniqueItems" : true,
          "items" : {
            "type" : "string",
            "enum" : [ "ns:concern_RiskAssessment", "ns:concern_Maintenance", "ns:concern_AssessmentAuthorizationAndMonitoring", "ns:concern_MediaProtection", "ns:concern_SystemAndServicesAcquisition", "ns:concern_IdentificationAndAuthentication", "ns:concern_IncidentResponse", "ns:concern_AuditAndAccountability", "ns:concern_ConfigurationManagement", "ns:concern_SystemAndInformationIntegrity", "ns:concern_AwarenessAndTraining", "ns:concern_SystemAndCommunicationsProtection", "ns:concern_ContingencyPlanning", "ns:concern_Planning", "ns:concern_ProgramManagement", "ns:concern_AccessControl", "ns:concern_PhysicalAndEnvironmentalProtection", "ns:concern_PersonnelSecurity" ]
          }
        },
        "ns:hasThreat" : {
          "title" : "Threat (CAPEC-based)",
          "description" : "Tells what threats (CAPEC attack patterns) a pattern describes with connection to component(s) and function(s",
          "type" : "array",
          "uniqueItems" : true,
          "items" : {
            "type" : "string",
            "enum" : [ "ns:threat_Flooding", "ns:threat_InformationGathering", "ns:threat_AuthenticationBypass", "ns:threat_EnvironmentManipulation", "ns:threat_PriviledgeEscalation", "ns:threat_InputDataManipulation", "ns:threat_ProtocolAnalysis", "ns:threat_SharedDataManipulation", "ns:threat_ManInTheMiddle", "ns:threat_Footprinting", "ns:threat_Malware", "ns:threat_Excavation", "ns:threat_IdentitySpoofing", "ns:threat_ContentSpoofing", "ns:threat_SessionManipulation", "ns:threat_BufferManipulation", "ns:threat_CodeInjection", "ns:threat_Interception", "ns:threat_ManipulationAPI", "ns:threat_ExcessiveAllocation" ]
          }
        }
      }
    }
  }
}

=== nets4geeks/SPCatalogMaker/catalogs/acctp/catalog/threatAD07_LogOfCloudApplicationLost.json
{
  "id": "threatAD07_LogOfCloudApplicationLost",
  "metadata": {
    "ns:textReviewContext": "Someone interacts with a cloud application",
    "ns:textName": "AD07 Log Of Cloud Application Lost",
    "ns:textReviewSolution": "Apply third-part log service",
    "ns:textURL": "",
    "ns:textReviewProblem": "Lost of cloud application log",
    "ns:textReference": "R30, R.31 Lost or compromise of operational or security logs [ENISA]"
  },
  "organization": {
    "ns:usesPattern": [],
    "ns:hasGroup": [],
    "ns:hasType": ["ns:type_ThreatPattern"],
    "ns:hasTemplate": [],
    "ns:relatesTo": [],
    "ns:isChildOf": []
  },
  "common": {
    "ns:hasArchitecturalLayer": [],
    "ns:hasResponseType": [],
    "ns:hasDomain": [],
    "ns:hasSecurityLevel": [],
    "ns:hasLifecycleStage": [],
    "ns:hasConstraintLevel": []
  },
  "context": {
    "ns:hasAffectedFunction": [],
    "ns:hasAffectedComponent": ["su:comp_CloudApplication"]
  },
  "security": {
    "ns:hasThreat": [],
    "ns:hasAggressor": ["su:comp_CloudApplication", "su:comp_ExternalService", "su:comp_RemoteUser"],
    "ns:hasAggressorRole": ["ns:role_Client"],
    "ns:hasWeakness": [],
    "ns:hasSTRIDE": ["ns:STRIDE_Repudiation"],
    "ns:hasSecurityConcern": []
  }
}

=== nets4geeks/SPCatalogMaker/catalogs/acctp/catalog/threatAE02_EDoSAttackToCloudApplication.json
{
  "id": "threatAE02_EDoSAttackToCloudApplication",
  "metadata": {
    "ns:textReviewContext": "Remote user interacts with a cloud application",
    "ns:textName": "AE02 EDoS Attack To Cloud Application",
    "ns:textReviewSolution": "",
    "ns:textURL": "",
    "ns:textReviewProblem": "EDoS (Economic Denial of Sustainability or Economic Denial of Service) attack against cloud application from the Internet",
    "ns:textReference": "MS-3: An attack that leads to an excessive use of resources that are billed for, resulting in an Economic Denial of Service (E-DoS) [SECCRIT]; R.16: ECONOMIC DENIAL OF SERVICE (EDOS) [ENISA]; Economic Denial of Service [QUIRC]; Economic Durability [Rath]"
  },
  "organization": {
    "ns:usesPattern": [],
    "ns:hasGroup": [],
    "ns:hasType": ["ns:type_ThreatPattern"],
    "ns:hasTemplate": [],
    "ns:relatesTo": [],
    "ns:isChildOf": []
  },
  "common": {
    "ns:hasArchitecturalLayer": [],
    "ns:hasResponseType": [],
    "ns:hasDomain": [],
    "ns:hasSecurityLevel": [],
    "ns:hasLifecycleStage": [],
    "ns:hasConstraintLevel": []
  },
  "context": {
    "ns:hasAffectedFunction": [],
    "ns:hasAffectedComponent": ["su:comp_CloudApplication"]
  },
  "security": {
    "ns:hasThreat": [],
    "ns:hasAggressor": ["su:comp_RemoteUser"],
    "ns:hasAggressorRole": ["ns:role_Client"],
    "ns:hasWeakness": [],
    "ns:hasSTRIDE": ["ns:STRIDE_Denial_of_Service"],
    "ns:hasSecurityConcern": []
  }
}

=== nets4geeks/SPCatalogMaker/catalogs/acctp/catalog/threatAA03_DataBreachByRemoteService.json
{
  "id": "threatAA03_DataBreachByRemoteService",
  "metadata": {
    "ns:textReviewContext": "Cloud application uses a remote service",
    "ns:textName": "AA03 Data Breach By Remote Service",
    "ns:textReviewSolution": "Replace the remote service by a local one; Apply data encryption;",
    "ns:textURL": "",
    "ns:textReviewProblem": "Data breach (information disclosure) by the remote service",
    "ns:textReference": ""
  },
  "organization": {
    "ns:usesPattern": [],
    "ns:hasGroup": [],
    "ns:hasType": ["ns:type_ThreatPattern"],
    "ns:hasTemplate": [],
    "ns:relatesTo": [],
    "ns:isChildOf": []
  },
  "common": {
    "ns:hasArchitecturalLayer": [],
    "ns:hasResponseType": [],
    "ns:hasDomain": [],
    "ns:hasSecurityLevel": [],
    "ns:hasLifecycleStage": [],
    "ns:hasConstraintLevel": []
  },
  "context": {
    "ns:hasAffectedFunction": [],
    "ns:hasAffectedComponent": ["su:comp_CloudApplication"]
  },
  "security": {
    "ns:hasThreat": [],
    "ns:hasAggressor": ["su:comp_ExternalService"],
    "ns:hasAggressorRole": ["ns:role_Server"],
    "ns:hasWeakness": [],
    "ns:hasSTRIDE": ["ns:STRIDE_Information_Disclosure"],
    "ns:hasSecurityConcern": []
  }
}

=== nets4geeks/SPCatalogMaker/catalogs/acctp/catalog/threatBA10_ServiceProviderLockIn.json
{
  "id": "threatBA10_ServiceProviderLockIn",
  "metadata": {
    "ns:textReviewContext": "Compliance manager works with cloud application",
    "ns:textName": "BA10 Service Provider Lock-In",
    "ns:textReviewSolution": "",
    "ns:textURL": "",
    "ns:textReviewProblem": "Service provider lock-in",
    "ns:textReference": "R.1: Lock-in (SaaS Lock-in, PaaS Lock-in, IaaS Lock-in) [ENISA]; OI-5: Contractual issues that emerge because of bankruptcy and potential switching costs [SECCRIT]"
  },
  "organization": {
    "ns:usesPattern": [],
    "ns:hasGroup": [],
    "ns:hasType": ["ns:type_ThreatPattern"],
    "ns:hasTemplate": [],
    "ns:relatesTo": [],
    "ns:isChildOf": []
  },
  "common": {
    "ns:hasArchitecturalLayer": [],
    "ns:hasResponseType": [],
    "ns:hasDomain": [],
    "ns:hasSecurityLevel": [],
    "ns:hasLifecycleStage": [],
    "ns:hasConstraintLevel": []
  },
  "context": {
    "ns:hasAffectedFunction": [],
    "ns:hasAffectedComponent": ["su:comp_CloudApplication"]
  },
  "security": {
    "ns:hasThreat": [],
    "ns:hasAggressor": ["su:comp_ComplianceManager"],
    "ns:hasAggressorRole": ["ns:role_Client"],
    "ns:hasWeakness": [],
    "ns:hasSTRIDE": [],
    "ns:hasSecurityConcern": []
  }
}

=== nets4geeks/SPCatalogMaker/catalogs/acctp/catalog/threatBA05_LackOfResourceIsolationOfCloudApplication.json
{
  "id": "threatBA05_LackOfResourceIsolationOfCloudApplication",
  "metadata": {
    "ns:textReviewContext": "Compliance manager works with cloud application",
    "ns:textName": "BA05 Lack Of Resource Isolation Of Cloud Application",
    "ns:textReviewSolution": "Define data isolation testing procedures (SLA);",
    "ns:textURL": "",
    "ns:textReviewProblem": "Lack of data, code, network isolation of cloud applications caused by misconfigurations and vulnerabilities of cloud infrastructure",
    "ns:textReference": "R.9 Isolation failure [ENISA]; Isolation Failure [QUIRC]; Data Isolation Testing Level [Casola];"
  },
  "organization": {
    "ns:usesPattern": [],
    "ns:hasGroup": [],
    "ns:hasType": ["ns:type_ThreatPattern"],
    "ns:hasTemplate": [],
    "ns:relatesTo": [],
    "ns:isChildOf": []
  },
  "common": {
    "ns:hasArchitecturalLayer": [],
    "ns:hasResponseType": [],
    "ns:hasDomain": [],
    "ns:hasSecurityLevel": [],
    "ns:hasLifecycleStage": [],
    "ns:hasConstraintLevel": []
  },
  "context": {
    "ns:hasAffectedFunction": [],
    "ns:hasAffectedComponent": ["su:comp_CloudApplication"]
  },
  "security": {
    "ns:hasThreat": [],
    "ns:hasAggressor": ["su:comp_ComplianceManager"],
    "ns:hasAggressorRole": ["ns:role_Client"],
    "ns:hasWeakness": [],
    "ns:hasSTRIDE": ["ns:STRIDE_Information_Disclosure","ns:STRIDE_Tampering"],
    "ns:hasSecurityConcern": []
  }
}

=== nets4geeks/SPCatalogMaker/catalogs/acctp/catalog/threatAD05_BackupOfCloudApplicationLost.json
{
  "id": "threatAD05_BackupOfCloudApplicationLost",
  "metadata": {
    "ns:textReviewContext": "Someone interacts with a cloud application",
    "ns:textName": "AD05 Backup Of CloudApplication Lost",
    "ns:textReviewSolution": "",
    "ns:textURL": "",
    "ns:textReviewProblem": "Lost of cloud application backup",
    "ns:textReference": "R.32: BACKUPS LOST, STOLEN [ENISA]; Data Retention [Rath]"
  },
  "organization": {
    "ns:usesPattern": [],
    "ns:hasGroup": [],
    "ns:hasType": ["ns:type_ThreatPattern"],
    "ns:hasTemplate": [],
    "ns:relatesTo": [],
    "ns:isChildOf": []
  },
  "common": {
    "ns:hasArchitecturalLayer": [],
    "ns:hasResponseType": [],
    "ns:hasDomain": [],
    "ns:hasSecurityLevel": [],
    "ns:hasLifecycleStage": [],
    "ns:hasConstraintLevel": []
  },
  "context": {
    "ns:hasAffectedFunction": [],
    "ns:hasAffectedComponent": ["su:comp_CloudApplication"]
  },
  "security": {
    "ns:hasThreat": [],
    "ns:hasAggressor": ["su:comp_CloudApplication", "su:comp_ExternalService", "su:comp_RemoteUser"],
    "ns:hasAggressorRole": ["ns:role_Client"],
    "ns:hasWeakness": [],
    "ns:hasSTRIDE": ["ns:STRIDE_Denial_of_Service"],
    "ns:hasSecurityConcern": []
  }
}

=== nets4geeks/SPCatalogMaker/catalogs/acctp/catalog/threatAD02_BrokenAccessControl.json
{
  "id": "threatAD02_BrokenAccessControl",
  "metadata": {
    "ns:textReviewContext": "Someone interacts with a cloud application",
    "ns:textName": "AD02 Broken Access Control",
    "ns:textReviewSolution": "Apply access control model; Apply access management;",
    "ns:textURL": "",
    "ns:textReviewProblem": "No access control or broken (weak) access control of the cloud application",
    "ns:textReference": "Broken Access Control [OWASP10]"
  },
  "organization": {
    "ns:usesPattern": [],
    "ns:hasGroup": [],
    "ns:hasType": ["ns:type_ThreatPattern"],
    "ns:hasTemplate": [],
    "ns:relatesTo": [],
    "ns:isChildOf": []
  },
  "common": {
    "ns:hasArchitecturalLayer": [],
    "ns:hasResponseType": [],
    "ns:hasDomain": [],
    "ns:hasSecurityLevel": [],
    "ns:hasLifecycleStage": [],
    "ns:hasConstraintLevel": []
  },
  "context": {
    "ns:hasAffectedFunction": [],
    "ns:hasAffectedComponent": ["su:comp_CloudApplication"]
  },
  "security": {
    "ns:hasThreat": [],
    "ns:hasAggressor": ["su:comp_CloudApplication", "su:comp_ExternalService", "su:comp_RemoteUser"],
    "ns:hasAggressorRole": ["ns:role_Client"],
    "ns:hasWeakness": [],
    "ns:hasSTRIDE": [],
    "ns:hasSecurityConcern": []
  }
}

=== nets4geeks/SPCatalogMaker/catalogs/acctp/catalog/threatBA01_MaliciousInsiderInCloudInfrastructure.json
{
  "id": "threatBA01_MaliciousInsiderInCloudInfrastructure",
  "metadata": {
    "ns:textReviewContext": "Compliance manager works with cloud application",
    "ns:textName": "BA01 Malicious Insider In Cloud Infrastructure",
    "ns:textReviewSolution": "Define Cost of Incident metrics;",
    "ns:textURL": "",
    "ns:textReviewProblem": "Malicious insider in cloud infrastructure causes security issues of cloud application",
    "ns:textReference": "OI-1: Malicious insiders in the cloud infrastructure provider [SECCRIT]; R.10: Cloud provider malicious insider - abuse of high privilege roles [ENISA]; Cloud Provider Malicious Insider [QUIRC]; TIS.021 [BDU]; Cost of Incidents, Mean Cost of Incidents, Mean Incident Recovery Cost [Casola];"
  },
  "organization": {
    "ns:usesPattern": [],
    "ns:hasGroup": [],
    "ns:hasType": ["ns:type_ThreatPattern"],
    "ns:hasTemplate": [],
    "ns:relatesTo": [],
    "ns:isChildOf": []
  },
  "common": {
    "ns:hasArchitecturalLayer": [],
    "ns:hasResponseType": [],
    "ns:hasDomain": [],
    "ns:hasSecurityLevel": [],
    "ns:hasLifecycleStage": [],
    "ns:hasConstraintLevel": []
  },
  "context": {
    "ns:hasAffectedFunction": [],
    "ns:hasAffectedComponent": ["su:comp_CloudApplication"]
  },
  "security": {
    "ns:hasThreat": [],
    "ns:hasAggressor": ["su:comp_ComplianceManager"],
    "ns:hasAggressorRole": ["ns:role_Client"],
    "ns:hasWeakness": [],
    "ns:hasSTRIDE": [],
    "ns:hasSecurityConcern": []
  }
}
